In [2]:
# Import in Pandas functions
import pandas as pd
import datetime
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

# The path to our CSV file
file = "Resources/CalendarData.csv"

# Read our AirBnB Calendar data into pandas
CalendarData = pd.read_csv(file)
CalendarData.head()

   listing_id        date available   price
0        2515  2018-10-01         t  $99.00
1        2515  2018-09-30         t  $89.00
2        2515  2018-09-29         t  $99.00
3        2515  2018-09-28         t  $99.00
4        2515  2018-09-27         t  $99.00

In [3]:

#Identify the number of lines in CalendarData DataFrame.
CalendarData.shape

(16182640, 4)

In [4]:
# Used the next line to work with 10,000 lines of data as opposed to the population.
# CalendarData = CalendarData[0:10000]

In [5]:
# Eliminate "$" from 'price' column.
CalendarData['price'] = CalendarData['price'].str.replace('$','')

In [6]:
# Eliminate "," from 'price' column.
CalendarData['price'] = CalendarData['price'].str.replace(',','')

In [7]:
# Identify make-up of CalendarData and display the tail of Panadas.
CalendarData.tail()

          listing_id        date available  price
16182635    21178032  2017-10-06         f    NaN
16182636    21178032  2017-10-05         f    NaN
16182637    21178032  2017-10-04         t  50.00
16182638    21178032  2017-10-03         t  50.00
16182639    21178032  2017-10-02         t  50.00

In [8]:
#Review of the CalendarData file after the "$" and "," are removed to change from string to float.
CalendarData.info

<bound method DataFrame.info of           listing_id        date available  price
0               2515  2018-10-01         t  99.00
1               2515  2018-09-30         t  89.00
2               2515  2018-09-29         t  99.00
3               2515  2018-09-28         t  99.00
4               2515  2018-09-27         t  99.00
5               2515  2018-09-26         t  99.00
6               2515  2018-09-25         t  99.00
7               2515  2018-09-24         t  99.00
8               2515  2018-09-23         t  99.00
9               2515  2018-09-22         t  99.00
10              2515  2018-09-21         t  99.00
11              2515  2018-09-20         t  99.00
12              2515  2018-09-19         t  99.00
13              2515  2018-09-18         t  99.00
14              2515  2018-09-17         t  99.00
15              2515  2018-09-16         t  99.00
16              2515  2018-09-15         t  99.00
17              2515  2018-09-14         t  99.00
18              2515  2018-09-13         t  99.00
19              2515  2018-09-12         t  99.00
20              2515  2018-09-11         t  99.00
21              2515  2018-09-10         t  99.00
22              2515  2018-09-09         t  99.00
23              2515  2018-09-08         t  99.00
24              2515  2018-09-07         t  99.00
25              2515  2018-09-06         t  99.00
26              2515  2018-09-05         t  99.00
27              2515  2018-09-04         t  99.00
28              2515  2018-09-03         t  99.00
29              2515  2018-09-02         t  99.00
...              ...         ...       ...    ...
16182610    21178032  2017-10-31         t  50.00
16182611    21178032  2017-10-30         t  50.00
16182612    21178032  2017-10-29         t  50.00
16182613    21178032  2017-10-28         t  50.00
16182614    21178032  2017-10-27         t  50.00
16182615    21178032  2017-10-26         t  50.00
16182616    21178032  2017-10-25         t  50.00
16182617    21178032  2017-10-24         t  50.00
16182618    21178032  2017-10-23         t  50.00
16182619    21178032  2017-10-22         t  50.00
16182620    21178032  2017-10-21         t  50.00
16182621    21178032  2017-10-20         t  50.00
16182622    21178032  2017-10-19         t  50.00
16182623    21178032  2017-10-18         t  50.00
16182624    21178032  2017-10-17         t  50.00
16182625    21178032  2017-10-16         t  50.00
16182626    21178032  2017-10-15         f    NaN
16182627    21178032  2017-10-14         f    NaN
16182628    21178032  2017-10-13         f    NaN
16182629    21178032  2017-10-12         t  50.00
16182630    21178032  2017-10-11         t  50.00
16182631    21178032  2017-10-10         t  50.00
16182632    21178032  2017-10-09         t  50.00
16182633    21178032  2017-10-08         t  50.00
16182634    21178032  2017-10-07         f    NaN
16182635    21178032  2017-10-06         f    NaN
16182636    21178032  2017-10-05         f    NaN
16182637    21178032  2017-10-04         t  50.00
16182638    21178032  2017-10-03         t  50.00
16182639    21178032  2017-10-02         t  50.00

[16182640 rows x 4 columns]>

In [12]:
CalendarData.columns = ['Listing ID', 'Date', 'Available', 'Price']
CalendarData.tail(20)

          Listing ID        Date Available  Price
16182614    21178032  2017-10-27         t   50.0
16182615    21178032  2017-10-26         t   50.0
16182616    21178032  2017-10-25         t   50.0
16182617    21178032  2017-10-24         t   50.0
16182618    21178032  2017-10-23         t   50.0
16182619    21178032  2017-10-22         t   50.0
16182620    21178032  2017-10-21         t   50.0
16182621    21178032  2017-10-20         t   50.0
16182622    21178032  2017-10-19         t   50.0
16182623    21178032  2017-10-18         t   50.0
16182624    21178032  2017-10-17         t   50.0
16182625    21178032  2017-10-16         t   50.0
16182629    21178032  2017-10-12         t   50.0
16182630    21178032  2017-10-11         t   50.0
16182631    21178032  2017-10-10         t   50.0
16182632    21178032  2017-10-09         t   50.0
16182633    21178032  2017-10-08         t   50.0
16182637    21178032  2017-10-04         t   50.0
16182638    21178032  2017-10-03         t   50.0
16182639    21178032  2017-10-02         t   50.0

In [13]:
# Drop all rows with no price data.
CalendarData = CalendarData.dropna()

In [14]:

CalendarData['Price'] = CalendarData['Price'].astype('float')

In [15]:
CalendarData.dtypes

Listing ID      int64
Date           object
Available      object
Price         float64
dtype: object

In [16]:
CalendarData.to_csv("Output/CalendarDatabyDate.csv")

In [17]:
DateGrouped_df = CalendarData.groupby(['Date'])
DateGrouped_df.head()

       Listing ID        Date Available  Price
0            2515  2018-10-01         t   99.0
1            2515  2018-09-30         t   89.0
2            2515  2018-09-29         t   99.0
3            2515  2018-09-28         t   99.0
4            2515  2018-09-27         t   99.0
5            2515  2018-09-26         t   99.0
6            2515  2018-09-25         t   99.0
7            2515  2018-09-24         t   99.0
8            2515  2018-09-23         t   99.0
9            2515  2018-09-22         t   99.0
10           2515  2018-09-21         t   99.0
11           2515  2018-09-20         t   99.0
12           2515  2018-09-19         t   99.0
13           2515  2018-09-18         t   99.0
14           2515  2018-09-17         t   99.0
15           2515  2018-09-16         t   99.0
16           2515  2018-09-15         t   99.0
17           2515  2018-09-14         t   99.0
18           2515  2018-09-13         t   99.0
19           2515  2018-09-12         t   99.0
20           2515  2018-09-11         t   99.0
21           2515  2018-09-10         t   99.0
22           2515  2018-09-09         t   99.0
23           2515  2018-09-08         t   99.0
24           2515  2018-09-07         t   99.0
25           2515  2018-09-06         t   99.0
26           2515  2018-09-05         t   99.0
27           2515  2018-09-04         t   99.0
28           2515  2018-09-03         t   99.0
29           2515  2018-09-02         t   99.0
...           ...         ...       ...    ...
4709         5178  2017-11-06         t   79.0
4723         5178  2017-10-23         t   79.0
4728         5178  2017-10-18         t   79.0
6184         5441  2017-10-22         t  126.0
6566         5803  2017-10-05         t   85.0
6567         5803  2017-10-04         t   85.0
6568         5803  2017-10-03         t   85.0
6569         5803  2017-10-02         t   85.0
6909         5945  2017-10-27         t  120.0
6910         5945  2017-10-26         t  120.0
6911         5945  2017-10-25         t  120.0
6912         5945  2017-10-24         t  120.0
6915         5945  2017-10-21         t  120.0
6916         5945  2017-10-20         t  120.0
6917         5945  2017-10-19         t  120.0
6919         5945  2017-10-17         t  120.0
6930         5945  2017-10-06         t  120.0
6931         5945  2017-10-05         t  120.0
6932         5945  2017-10-04         t  120.0
6933         5945  2017-10-03         t  120.0
11315        8110  2018-10-02         t  105.0
12768        8371  2017-10-08         t   80.0
12769        8371  2017-10-07         t   80.0
12770        8371  2017-10-06         t   80.0
18244       11943  2017-10-07         t  150.0
19339       12299  2017-10-07         t  120.0
27010       14468  2018-10-02         t   99.0
32275       16076  2018-10-02         t   94.0
42130       19159  2018-10-02         t  140.0
42557       19169  2018-10-02         t  285.0

[1830 rows x 4 columns]

In [18]:
# Identify the top Dates with number of purchases, average purchases, and total purchase value
Date_Spend_sum = CalendarData.groupby('Date')['Price'].sum()
Date_Spend_mean = CalendarData.groupby('Date')['Price'].mean()
Date_Spend_count = CalendarData.groupby('Date')['Price'].count()

# Sort data on date
Date_Spend = pd.DataFrame({'Total Spend by Date':Date_Spend_sum,'Average Spend by Date':Date_Spend_mean,'Number or Listings by Date':Date_Spend_count})

# Print output
Date_Spend.sort_values('Total Spend by Date',ascending=False)

,Total Spend by Date,Average Spend by Date,Number or Listings by Date
Date,,,
2017-12-22,3276775.0,174.389303,18790
2017-12-23,3208079.0,175.698505,18259
2018-03-23,3194041.0,172.343441,18533
2018-03-24,3185712.0,172.303099,18489
2018-03-30,3177752.0,173.316171,18335
2017-12-21,3172891.0,166.643435,19040
2018-03-17,3171282.0,171.541191,18487
2017-12-16,3163654.0,167.584172,18878
2017-12-15,3152663.0,167.409887,18832
2018-03-16,3148892.0,170.838325,18432
2017-12-20,3141270.0,164.103542,19142
2017-12-18,3137809.0,163.189567,19228
2017-12-19,3133331.0,162.990585,19224
2017-12-24,3129396.0,175.512956,17830
2017-12-17,3128898.0,163.405995,19148
2018-03-10,3119461.0,168.856826,18474
2018-03-09,3115398.0,168.691683,18468
2018-03-03,3096421.0,168.201478,18409
2018-03-02,3089286.0,167.877731,18402
2018-03-21,3085107.0,166.259269,18556
2018-03-20,3081724.0,166.139630,18549
2018-03-22,3079137.0,166.027014,18546
2018-03-19,3074342.0,166.001188,18520
2018-03-18,3072458.0,166.069834,18501
2018-03-25,3070604.0,166.257188,18469
2017-12-25,3061068.0,176.156299,17377
2018-03-26,3059336.0,166.078715,18421
2017-12-13,3058891.0,162.335668,18843
2018-03-28,3054506.0,166.485311,18347
2018-03-27,3052916.0,166.154131,18374
...,...,...,...
2017-11-03,1991861.0,168.987953,11787
2017-10-29,1924288.0,169.108709,11379
2017-10-23,1830395.0,169.842721,10777
2017-10-24,1826399.0,169.095362,10801
2017-10-25,1792386.0,168.030937,10667
2017-10-28,1791136.0,176.553573,10145
2017-10-17,1774451.0,172.460978,10289
2017-10-22,1771432.0,171.004151,10359
2017-10-27,1753548.0,176.431029,9939
2017-10-16,1751710.0,173.453807,10099
2017-10-26,1734346.0,168.792798,10275
2017-10-18,1720072.0,170.862422,10067
2017-10-15,1664199.0,176.685317,9419
2017-10-19,1643125.0,172.054974,9550
2017-10-20,1618629.0,179.747807,9005
2017-10-21,1610574.0,177.278371,9085
2017-10-10,1579408.0,178.262754,8860
2017-10-11,1561217.0,177.673495,8787
2017-10-09,1475960.0,183.851520,8028
2017-10-12,1472073.0,178.023098,8269
2017-10-14,1442821.0,186.966567,7717
2017-10-13,1422765.0,187.774185,7577
2017-10-08,1156657.0,196.010337,5901
2017-10-04,1087551.0,194.727126,5585
2017-10-05,1029085.0,198.473481,5185
2017-10-03,977581.0,198.493604,4925
2018-10-02,954680.0,168.671378,5660
2017-10-06,911827.0,229.563696,3972
2017-10-07,879983.0,233.479172,3769
2017-10-02,431094.0,201.917564,2135

In [19]:
# Describe Date_Spend
Date_Spend.describe()

       Total Spend by Date  Average Spend by Date  Number or Listings by Date
count         3.660000e+02             366.000000                  366.000000
mean          2.597756e+06             171.534631                15252.393443
std           4.100013e+05               9.215039                 2767.810426
min           4.310940e+05             156.214669                 2135.000000
25%           2.529710e+06             164.439130                14389.000000
50%           2.572220e+06             173.185781                14755.000000
75%           2.838414e+06             174.172164                17769.500000
max           3.276775e+06             233.479172                19228.000000

In [20]:
Date_Spend.info()

<class 'pandas.core.frame.DataFrame'>
Index: 366 entries, 2017-10-02 to 2018-10-02
Data columns (total 3 columns):
Total Spend by Date           366 non-null float64
Average Spend by Date         366 non-null float64
Number or Listings by Date    366 non-null int64
dtypes: float64(2), int64(1)
memory usage: 11.4+ KB

In [21]:
Date_Spend.to_csv("Output/Date_Spend.csv")

In [22]:
# Input the data about the holidays using years to represent each day of the holiday weekend for funtionality
Rental_Data = {'TG 2017': {2016: 2653192, 2017: 2745982, 2018: 2909169, 2019: 2958551}, 
                'Christmas 2017': {2016: 3276775, 2017: 3208079, 2018: 3129396, 2019: 3061068},
                'NYE 2018': {2016: 2871282, 2017: 2894549, 2018: 2683243, 2019: 0}, 
                'Memorial 2018': {2016: 2612120, 2017: 2522906, 2018: 2518031, 2019: 0},
                'July 4th 2018': {2016: 2529429, 2017: 2531422, 2018: 2532631, 2019: 0},
                'Labor 2018': {2016: 2673235, 2017: 2745982, 2018: 2909169, 2019: 0}}
# Set key for year and holiday data
year_data = {}
holidays = []

# Create for loop to cycle through data and append new data to create bar chart
for key, holiday_dict in Rental_Data.items():
    holidays.append(key)
    for year, revenue in sorted(holiday_dict.items()): 
        if year not in year_data:
            year_data[year] = []
        year_data[year].append(revenue)

# Use year data sorted in a logical way
years = sorted(year_data.keys())
year_sum = [0]*len(holidays)
bar_graphs = []

# Use year data to loop through data and reserve the year information
for year in years:
    graph = plt.bar(holidays, year_data[year], bottom=year_sum)
    bar_graphs.append(graph[0])
    year_sum = [year_sum[i] + year_data[year][i] for i in range(len(holidays))]
    
# Rotate the x-axis lables for readability    
plt.xticks(rotation=-30) 
# Creating title for y-axis
plt.ylabel('Revenue')
# Creating title for the plot
plt.title('Revenue During 2017 - 2018 Holidays')
# Creating legend for the plot
plt.legend(('Day 1', 'Day 2', 'Day 3', 'Day 4'), loc = 1, frameon = 'false')
# Store the plot
plt.savefig("Output/Revenue_for_Holidays.png")
# Show the plot
plt.show()